### ISSUE TITLE
[All events this year] Inconsistency between local and live

### ISSUE THREAD

**Issue by toubou91** [coderetreat/coderetreat.github.io#238]
Hi guys, I see there is an inconsistency between my local:
![screen shot 2017-11-07 at 07 44 21](https://user-images.githubusercontent.com/5684688/32513545-cb51bb52-c3fa-11e7-8a7d-8b452b4d6f67.png)

and the live instance of the website:
![screen shot 2017-11-07 at 07 44 46](https://user-images.githubusercontent.com/5684688/32513548-ccf0aa04-c3fa-11e7-980c-7bbad020c694.png)

_To be honest, I haven't digged into the code that much in order to pinpoint the issue, but I would like to first hear your opinion on that one (whether it is just a miss from my side or a miss in the implementation of the site itself); then, we can take it from there._

**Comment by apandichi** [comment]
Hi @toubou91. In your example for the live instance of the website, you selected "The Netherlands" instead of "Netherlands". Your event is live as well, under the "Netherlands" country.
The only inconsistency that might need fixing is to change the country name for one of these two events. Which one do you think it should be?

**Comment by toubou91** [comment]
Personally, I better like "Netherlands" and I believe it should be consistent, so that we avoid situations like that in the future.

Shall I submit a PR?

**Comment by apandichi** [comment]
Thank you, much appreciated!
